language: crystal

os:
  - linux
  - osx

before_deploy:
  - mkdir build
  - crystal build src/mint.cr -o build/mint-${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME --release --no-debug

deploy:
  - provider: s3
    access_key_id: AKIAIQDWL22LBYSJBFBQ
    skip_cleanup: true
    secret_access_key:
      secure: KZmcNoXWMQiMWWgHWCktbjV8LBqcqqvxpzL/eFjn8uOFJ222lHkSLyOe08vFM8CScYTQjMKwTBwkvRNgaMkKY9q4pikoJfkC1T01xUW17tTLh3ps06Yc5cdxnZT9KllRKDr26SISnpBbRCY42BuwmL97stFOjFPM/g9JC3z/oyRE0+B2oEc+M+d6oXijsBxgp4jvkMtbWLFSPjM0NTJwcnkp6ZwgsAzdGislaqbSEKkMT4SMN4PBWHg4z+1sV25d+ZwjYBUFk9Ll5aBTgP7SW6vRsAXBPUPwREF4scRuuMMcYvbAU3efp1gGKAC13YYniyLSZ8HyFrR5O1jVkn02PcszdCRaopZW61XTYTJxiLumFN1HR+ej5ZIcLpLVyTtYs7ABS7vxrfRNVM6dDPKAQ6IRg/hiL3C8HzmhC55N4TRYzGV8bBgBOmoOe7CiWV67k6vzxyaDWE6kfhzeZnHKdXU4SPFrvI+uTo8p0PzsTI8qMAXfhc8OrIKDQtencaVq/Vyj3JaXUymeDsXSVAqLPFEufTx5cQTmmFzHZT5I3XSiMDgVaM05O4Yi2uSt9FUEUX8Mf8hNAoyTSnT192NvgccTnvflkLH0f0PiQrQTpaeB72VJzCkAsPFxH4ruTZtOfiZyT6mHUkqcXjyH6uNjvQsb11BhTnIBAPerayOi0Xo=
    bucket: mint-lang
    local_dir: build
    acl: public_read
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: j24NX9YWlWigJ1L5csx+GpbcLBY0RUzD029uFBNGEN9C1nXGIdtXVaxUrd+vCqJf3I40qykKZdajwW8bkt/79KDGDehytDPczP6FKk1NBMR+6usNzgzTMQLg0e7AGn7tVrBRS2cZUaiB6V23K7TNt6O67/jf55CgMsCUXAqycs8TowcXQ7KQvLrN1c2L1X5ypzGgF6Lc484ry9NVsXmr0fcKMJfCaOlJxMhg479GNPwS3EwGs9GrT5STLO+XcssfdFE8ij6eTE7SDtEQgm2MNlysQ6pPbs24k77coC6bVm/KIJMHyResBmOuKRLiY07fEt6LemdxOcfwK59LZCh4ccdawUhI/EhGg6K8QLXeStmRw835pD2juNqfg9Icje1eCkLQJ+6I+FD9QhwRr2ix+yCzVYX3Vfe6wCKqNfnc/kEz/z2UubXrcZeADsOTWIbJXOx0pLue9SnPFXVc/kjp1tUtgQMaZeC8dAhO0Il6miRP5uSEO6Fd/LRFs0LxHoSpbrPLbXggVQd9qm1RKIHaksn8Ajy35DO+vmA0XfXeuAtSlSECsyKXmueGnF+yTXAy/8+S/eKQQbfIAMRUx0SIPKdS86Z5ziWU/afcZNaWWtgI73So88DUG3rPlPwLayV6BpwVxMKbbyDMBOUxWIcZ17orr3KhXVJgpklrFVrdUuU=
    file_glob: true
    file: build/*
    on:
      tags: true
