name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Crystal
      uses: oprypin/install-crystal@v1.2.4
    
    - name: Checkout Source
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: shards install
  
    - name: Run Tests
      run: crystal spec --error-on-warnings --error-trace
    
    - name: Check Formatting
      run: crystal tool format --check
    
    - name: Run Ameba
      run: bin/ameba
    
    - name: Run Core Tests
      run: make test-core
