name: Linux CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Crystal
      uses: oprypin/install-crystal@v1.2.4

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Install Dependencies
      run: shards install

    - name: Run Tests
      run: crystal spec --error-on-warnings --error-trace

    - name: Check Formatting
      run: crystal tool format --check

    - name: Run Ameba
      run: bin/ameba

    - name: Run Core Tests
      run: make test-core

    - name: Build Binary
      run: |
        mkdir build
        docker-compose run --rm app crystal build src/mint.cr -o build/mint-${GITHUB_REF_SLUG}-linux --release --static

    - name: Upload to S3
      uses: shallwefootball/upload-s3-action@v1.1.2
      if: github.ref == 'refs/heads/master'
      with:
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        aws_key_id: ${{ secrets.AWS_KEY }}
        source_dir: build
        destination_dir: ''

    - name: Upload to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')
      uses: skx/github-action-publish-binaries@release-0.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ env.GITHUB_REF_SLUG }}
        args: 'build/*'
